version: '3.8'

services:
  authservice:
    build:
      context: ./AuthService
    ports:
      - "5102:5102"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./AuthService/.env
    depends_on:
      - redis
      - db
    networks:
      - booknetwork

  bookservice:
    container_name: bookservice
    build:
      context: ./BookService
    ports:
      - "5294:5294"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./BookService/.env

    depends_on:
      - redis
      - db
    networks:
      - booknetwork

  reviewservice:
    container_name: reviewservice
    build:
      context: ./ReviewService
    ports:
      - "5222:5222"
      - "5223:5223" # REST
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./ReviewService/.env
    depends_on:
      - redis
      - db
    networks:
      - booknetwork

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - authservice
      - bookservice
      - reviewservice
    networks:
      - booknetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - booknetwork

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "E!R3kF@a91sdPO8z"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - booknetwork

networks:
  booknetwork:
    driver: bridge